stages:
  - build
  - deploy

build-job:
  stage: build
  variables:
    PYTHONBASE: '3.11-bullseye'
    CUDA_INSTALL: 'no'
    DUID: '991'
    DGID: '988'
  script:
    - make build PYTHONBASE=$PYTHONBASE CUDA_INSTALL=$CUDA_INSTALL UID=$DUID GID=$DGID
    - echo "PYTHONBASE=$PYTHONBASE" >>build.env
  artifacts:
    reports:
      dotenv: build.env

deploy-job:
  stage: deploy
  variables:
    PYLAB: 'torch'
    DOCKER_ARGS: ''
  script:
    - make tag_pylab PYTHONBASE=$PYTHONBASE PYLAB=$PYLAB
    - make pylab PYTHONBASE=$PYTHONBASE DOCKER_ARGS=$DOCKER_ARGS
    - make rlab PYTHONBASE=$PYTHONBASE DOCKER_ARGS=$DOCKER_ARGS
