stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - make build CUDA_INSTALL=

deploy-job:
  stage: deploy
  script:
    - make tag_pylab PYLAB=torch
    - make pylab DOCKER_ARGS=
    - make rlab DOCKER_ARGS=
