ARG PYTHONBASE
FROM pylab-common:${PYTHONBASE}

ARG CUDA_INSTALL
ARG PYTHONBASE
ARG PIPPROXY

RUN <<EOT
#!/usr/bin/env bash
. /usr/local/sbin/init_lab.sh
pip_install "-r /usr/local/etc/requirements_torch.txt"
EOT
