ARG PYTHONBASE
FROM pylab-mini:${PYTHONBASE}

ARG PYTHONBASE
ARG PIPPROXY

RUN <<EOT
#!/usr/bin/env bash
. /usr/local/sbin/init_lab.sh
pip_install "-r /usr/local/etc/requirements_common.txt"
EOT

RUN <<EOT
#!/usr/bin/env bash
. /usr/local/sbin/init_lab.sh
pip_install "-r /usr/local/etc/requirements_${PYTHONMAJOR}.txt"
EOT

RUN <<EOT
#!/usr/bin/env bash
. /usr/local/sbin/init_lab.sh
pip_install "-r /usr/local/etc/requirements_repos.txt"
EOT
