ARG PYTHONBASE=latest
FROM pylab-common:${PYTHONBASE}

ARG CUDA_INSTALL
ARG PIPPROXY

USER root

RUN <<EOT
#!/usr/bin/env bash
. /usr/local/sbin/init_lab.sh
if [ "zzz${CUDA_INSTALL}" == "zzzyes" ]
then
    pip_install "tensorflow[and-cuda]"
else
    pip_install "tensorflow"
fi
pip_install "-r /usr/local/etc/requirements_tf.txt"
EOT

USER ${USER}

ENTRYPOINT [ "/usr/bin/tini", "--" ]
CMD [[ -x "/notebook/${USERLAB}" ]] && "/notebook/${USERLAB}" || "/usr/local/sbin/jupyterlab.sh"
