ARG PYTHONBASE
FROM pylab-common:${PYTHONBASE}

ARG CUDA_INSTALL
ARG PYTHONBASE
ARG PIPPROXY

RUN <<EOT
#!/usr/bin/env bash
. /usr/local/sbin/init_lab.sh
if [ "zzz${CUDA_INSTALL}" == "zzzyes" ]
then
    pip_install "jax[cuda12_pip] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
else
    pip_install "jax[cpu]"
fi
EOT
