title: Docker Image Inheritance Model {
  near: top-center
  shape: text
  style: {
    font-size: 20
    bold: true
  }
}

direction: down

"python:3.11-bullseye" -> "pyrlab-base:3.11-bullseye"
"pyrlab-base:3.11-bullseye" -> "pylab-mini:3.11-bullseye" -> "pylab-common:3.11-bullseye"
"pyrlab-base:3.11-bullseye" -> "rlab-base:3.11-bullseye" -> "rlab:3.11-bullseye"
"pylab-common:3.11-bullseye" -> "pylab-tf:3.11-bullseye"
"pylab-common:3.11-bullseye" -> "pylab-torch:3.11-bullseye"
"pylab-common:3.11-bullseye" -> "pylab-jax:3.11-bullseye"
