ARG PYTHONBASE
FROM pylab-mini:${PYTHONBASE}

ARG CUDA_INSTALL
ARG PYTHONBASE
ARG PIPPROXY
ARG PIPHOST

RUN <<EOT
#!/usr/bin/env bash
. init.sh
pip_install "-r requirements_common.txt"
pip_install "-r requirements_${PYTHONMAJOR}.txt"
python repos.py
EOT
